spring:
  datasource:
    url: jdbc:mysql://39.106.29.164:3307/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 605684650deng
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: org.h2.Driver
    #schema: classpath:db/schema-h2.sql
    #data: classpath:db/data-h2.sql
    #url: jdbc:h2:mem:test
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml